image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - Build production image

build production:
  stage: Build production image
  only:
  - master
  script:
  - chmod +x ./setup.env.sh
  - ./setup.env.sh
  - docker info
  - docker-compose up -d --build
  # - docker run -d -p 80:80 --name tickytook-frontend jeshio/tickytook-frontend
