image: docker:stable

stages:
  - Deploy

docker build:
  stage: Build image
  script:
  - docker info
  - docker run -d -p 80:80 --name tickytook-frontend jeshio/tickytook-frontend

# deploy:
#   stage: Deploy
#   script:
#     - echo "Connect to server"
#     - ssh 