image: docker:stable

stages:
  - Build image

docker build:
  stage: Build image
  script:
  - docker info
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker-compose up -d --build
  # - docker run -d -p 80:80 --name tickytook-frontend jeshio/tickytook-frontend
