image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - Build image

docker build:
  stage: Build image
  script:
  - docker info
  - docker-compose up -d --build
  # - docker run -d -p 80:80 --name tickytook-frontend jeshio/tickytook-frontend
